import type { Recipe } from '@/types/recipe.types';

export const RECIPE_DATA: Recipe[] = [
    { id: "r125", masterId: "m76", category: "Dinner", title: "Garlic Broccoli Stir-Fry" },
    { id: "r44", masterId: "m157", category: "Bowls", title: "Quinoa Burrito Bowl" },
    { id: "r196", masterId: "m5", category: "Cookies", title: "Flourless Peanut Cookies" },
    { id: "r77", masterId: "m124", category: "Soups", title: "Turmeric Lentil Soup" },
    { id: "r13", masterId: "m188", category: "Tempeh", title: "Crumble Tempeh Taco" },
    { id: "r93", masterId: "m108", category: "Salad-Bombs", title: "Strawberry Spinach Mix" },
    { id: "r164", masterId: "m37", category: "Smoothies", title: "Chocolate Peanut Banana" },
    { id: "r52", masterId: "m149", category: "Stuffed-Veggie-Mains", title: "Stuffed Delicata Rings" },
    { id: "r31", masterId: "m170", category: "Stews", title: "Spicy Lentil Wat" },
    { id: "r111", masterId: "m90", category: "Lunch", title: "Roasted Vegetable Soup" },
    { id: "r143", masterId: "m58", category: "Dips", title: "Zesty Herb Guacamole" },
    { id: "r8", masterId: "m193", category: "Tofu", title: "Lemon Marinated Tofu" },
    { id: "r180", masterId: "m21", category: "Dessert", title: "Lemon Blueberry Tart" },
    { id: "r61", masterId: "m140", category: "Chili", title: "Lentil Butternut Chili" },
    { id: "r139", masterId: "m62", category: "Dips", title: "Spinach Artichoke Crock" },
    { id: "r2", masterId: "m199", category: "Tofu", title: "Sticky Sesame Tofu" },
    { id: "r148", masterId: "m53", category: "Basics", title: "Fluffy White Quinoa" },
    { id: "r84", masterId: "m117", category: "Roasted", title: "Lemon Asparagus Tray" },
    { id: "r121", masterId: "m80", category: "Dinner", title: "Lentil Bolognese Pasta" },
    { id: "r174", masterId: "m27", category: "Baked", title: "Baked Cinnamon Apples" },
    { id: "r40", masterId: "m161", category: "One-Pot-Wonders", title: "Lentil Shepherd Pie" },
    { id: "r159", masterId: "m42", category: "Slow-Cooker-Bombs", title: "Slow Split Pea" },
    { id: "r98", masterId: "m103", category: "Dressing-Bombs", title: "Ginger Sesame Glaze" },
    { id: "r5", masterId: "m196", category: "Tofu", title: "Miso Maple Tofu" },
    { id: "r69", masterId: "m132", category: "Pizza", title: "Roasted Veggie Flatbread" },
    { id: "r131", masterId: "m70", category: "Appetizers", title: "Cauliflower Buffalo Bites" },
    { id: "r187", masterId: "m14", category: "Raw", title: "Zucchini Noodles Marinara" },
    { id: "r22", masterId: "m179", category: "Veggie-Burgers", title: "Curried Vegetable Burger" },
    { id: "r151", masterId: "m50", category: "Basics", title: "Toasted Seed Topper" },
    { id: "r114", masterId: "m87", category: "Breakfast", title: "Maple Pecan Oats" },
    { id: "r58", masterId: "m143", category: "Chili", title: "Pumpkin Black Bean" },
    { id: "r168", masterId: "m33", category: "Smoothies", title: "Matcha Mint Green" },
    { id: "r102", masterId: "m99", category: "Dressing-Bombs", title: "Tomato Basil Italian" },
    { id: "r14", masterId: "m187", category: "Tempeh", title: "Balsamic Rosemary Tempeh" },
    { id: "r146", masterId: "m55", category: "Basics", title: "Fluffy Brown Rice" },
    { id: "r81", masterId: "m120", category: "Roasted", title: "Garlic Roasted Medley" },
    { id: "r127", masterId: "m74", category: "Dinner", title: "Tomato Gnocchi Skillet" },
    { id: "r177", masterId: "m24", category: "Dessert", title: "Chocolate Avocado Mousse" },
    { id: "r36", masterId: "m165", category: "One-Pot-Wonders", title: "Coconut Chickpea Curry" },
    { id: "r108", masterId: "m92", category: "Lunch", title: "Falafel Pocket Lunch" },
    { id: "r48", masterId: "m153", category: "Bowls", title: "Goddess Broccoli Bowl" },
    { id: "r193", masterId: "m8", category: "Cookies", title: "Chocolate Chip Cookies" },
    { id: "r73", masterId: "m128", category: "Soups", title: "Roasted Tomato Soup" },
    { id: "r135", masterId: "m66", category: "Appetizers", title: "Spinach Artichoke Cups" },
    { id: "r183", masterId: "m18", category: "Dessert", title